version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: "laravel-php"
    volumes:
      - ./src:/src
    working_dir: /src

  postgres:
    restart: always
    image: postgres:10-alpine
    container_name: "laravel-postgres"
    environment:
      POSTGRES_DB: vuesplash
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 5432:5432
    volumes:
      - ./postgresql:/var/lib/postgresql/data
